Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,7 +9,6 @@ jobs:
   steps:
    - checkout
    - setup_remote_docker
-
    - run: 
       name: Setup environment
       command: |
@@ -26,13 +25,42 @@ jobs:
        EOF
    - run: mkdir -p "${GOPATH_BASE}"
    - run: mkdir -p "${GOPATH_HEAD}/bin"
-       
+   - run:
+       name: Build application container
+       command: |
+         go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+         [ ! -e bin ] && mkdir bin;
+         cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+         docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+         docker network create --driver bridge secdevops-net
+   - run:
+       name: Run application in background
+       command: |
+         docker run \
+             --network secdevops-net \
+             --name invoicer \
+             ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} 
+          background: true
+
+   - run:
+       name: ZAP baseline test of application
+       # Only fail on error code 1, which indicates at least one FAIL was found.
+       # error codes 2 & 3 indicate WARN or other, and should not break the run
+       command: |
+         (
+         docker pull owasp/zap2docker-weekly && \
+         docker run \
+             --network secdevops-net \
+             -t owasp/zap2docker-weekly zap-baseline.py \
+             -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+             -t http://invoicer:8080/ \
+             || if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+         )
    - run:
       name: Testing application
       command: |
           go test \
           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
-
    - deploy:
        command: |
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
