CircleCI with ZAP test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,49 +1,69 @@
 version: 2
 jobs:
- build:
-  # Variable expansion in working_directory not supported at this time
-  # Testing GIT
-  # You will need to modify the code below to reflect your github account/repo setup
-  working_directory: /go/src/github.com/Uuteeff/invoicer-chapter2
-  docker:
-   - image: circleci/golang:1.10
-  steps:
-   - checkout
-   - setup_remote_docker
+  build:
+    # Variable expansion in working_directory not supported at this time
+    # You will need to modify the code below to reflect your github account/repo setup
+    working_directory: /go/src/github.com/Securing-DevOps/invoicer-chapter3
+    docker:
+      - image: circleci/golang:1.8
+    environment:
+      GO15VENDOREXPERIMENT: 1
+    branches:
+      only:
+        - master
+    steps:
+      - checkout
+      - setup_remote_docker
 
-   - run: 
-      name: Setup environment
-      command: |
-       gb="/src/github.com/${CIRCLE_PROJECT_USERNAME}";
-       if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then
-         dr="securingdevops"
-       else
-         dr=$DOCKER_USER
-       fi
-       cat >> $BASH_ENV << EOF
-       export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
-       export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
-       export DOCKER_REPO="$dr"
-       EOF
-   - run: mkdir -p "${GOPATH_BASE}"
-   - run: mkdir -p "${GOPATH_HEAD}/bin"
-       
-   - run:
-      name: Testing application
-      command: |
-          go test \
-          github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
+      - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
+      - run: echo 'export GOPATH_BASE="${GOPATH_HEAD}/src/github.com/${CIRCLE_PROJECT_USERNAME}"' >> $BASH_ENV
+      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
+      - run: mkdir -p "${GOPATH_BASE}"
+      - run: mkdir -p "${GOPATH_HEAD}/bin"
+      - run: go get github.com/govend/govend
 
-   - deploy:
-       command: |
-         if [ "${CIRCLE_BRANCH}" == "master" ]; then
-           docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-           go install --ldflags '-extldflags "-static"' \
-           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-           mkdir bin;
-           cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-           docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-           docker images --no-trunc | awk '/^app/ {print $3}' | \
-             sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
-           docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
-         fi
+      - run:
+          name: Build application container
+          command: |
+            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+            [ ! -e bin ] && mkdir bin;
+            cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+
+      - run:
+          name: Run application in background
+          command: |
+            docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
+          background: true
+
+      - run:
+          name: ZAP baseline test of application
+          # Only fail on error code 1, which indicates at least one FAIL was found.
+          # error codes 2 & 3 indicate WARN or other, and should not break the run
+          command: |
+            (
+            docker pull owasp/zap2docker-weekly && \
+            docker run -t owasp/zap2docker-weekly zap-baseline.py \
+                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+                -t http://172.17.0.2:8080/ || \
+            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+            )
+
+      - run:
+          name: Test dependencies are up to date
+          command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+
+      - deploy:
+          # Push application container to dockerhub
+          command: |
+            if [ "${CIRCLE_BRANCH}" == "master" ]; then
+                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+                echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
+                go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+                mkdir bin;
+                cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+                docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+                docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
+                docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
+            fi
+            
