zap test in pipeline

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,36 +22,36 @@ jobs:
    - run: mkdir -p "${GOPATH_HEAD}/bin"
    - run: go get github.com/govend/govend
 
-   # - run:
-   #     name: Build application container
-   #     command: |
-   #       go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-   #       [ ! -e bin ] && mkdir bin;
-   #       cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-   #       docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+   - run:
+       name: Build application container
+       command: |
+         go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+         [ ! -e bin ] && mkdir bin;
+         cp "${GOPATH_HEAD}/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+         docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
 
-   # - run:
-   #     name: Run application in background
-   #     command: |
-   #       docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
-   #     background: true
+   - run:
+       name: Run application in background
+       command: |
+         docker run ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}
+       background: true
 
-   # - run:
-   #     name: ZAP baseline test of application
-   #     # Only fail on error code 1, which indicates at least one FAIL was found.
-   #     # error codes 2 & 3 indicate WARN or other, and should not break the run
-   #     command: |
-   #       (
-   #       docker pull owasp/zap2docker-weekly && \
-   #       docker run -t owasp/zap2docker-weekly zap-baseline.py \
-   #           -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
-   #           -t http://172.17.0.2:8080/ || \
-   #       if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
-   #       )
-   # - run:
-   #     name: Test dependencies are up to date
-   #     command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
-   #
+   - run:
+       name: ZAP baseline test of application
+       # Only fail on error code 1, which indicates at least one FAIL was found.
+       # error codes 2 & 3 indicate WARN or other, and should not break the run
+       command: |
+         (
+         docker pull owasp/zap2docker-weekly && \
+         docker run -t owasp/zap2docker-weekly zap-baseline.py \
+             -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
+             -t http://172.17.0.2:8080/ || \
+         if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
+         )
+   - run:
+       name: Test dependencies are up to date
+       command: 'GOPATH="${GOPATH_HEAD}"; ( cd ${GOPATH_BASE}/${CIRCLE_PROJECT_REPONAME} && govend -u --prune && git diff --quiet )'
+
    - run:
       name: Testing application
       command: |
@@ -59,24 +59,15 @@ jobs:
           github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
 
    - deploy:
-       # Push application container to dockerhub
-       # command: |
-       #   if [ "${CIRCLE_BRANCH}" == "master" ]; then
-       #       docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-       #       echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
-       #       go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-       #       mkdir bin;
-       #       cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-       #       docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-       #       docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
-       #       docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
-       #   fi
-        command: |
-            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
-            echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
-            go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
-            mkdir bin;
-            cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
-            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
-            docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
-            docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
+       Push application container to dockerhub
+       command: |
+         if [ "${CIRCLE_BRANCH}" == "master" ]; then
+             docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
+             echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
+             go install --ldflags '-extldflags "-static"' github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME};
+             mkdir bin;
+             cp "$GOPATH_HEAD/bin/${CIRCLE_PROJECT_REPONAME}" bin/invoicer;
+             docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
+             docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
+             docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
+         fi
